title:              Kathrin Spendier
email:              kathrin.spendier@xprize.org
description:        Technical Prize Director Quantum Applications - Educator - Researcher
author:             Kathrin Spendier
baseurl:            "/about-me"
url:                "spendierk.github.io"

# Social Profiles
twitter_username:   kathrin_sp
github_username:    spendierk
linkedin_username:  kathrin-spendier-1ks

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
